#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Jason Tripp
"""E1: the TED5 archive codec and the 16-byte name field.

Two things are being defended here. One is that the parser accepts exactly
what `FGamemaps::Open` accepts -- no stricter, or the editor refuses maps the
game plays; no looser, or it produces files the game rejects. The other is
losslessness: three planes, every raw name byte, and the record's own
structure surviving a round trip unchanged.

The E0 fixtures are read here on purpose. They are generated by a different
implementation that makes different legal encoding choices, so parsing them
tests the decoder rather than the writer's mirror image.
"""

from __future__ import annotations

import importlib.util
import struct
import sys
import unittest
from dataclasses import replace
from pathlib import Path

EDITOR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(EDITOR))

from ec7edit_core.archive import (
    FIRST_RECORD_BYTES,
    LATER_RECORD_BYTES,
    MAP_MARKER,
    MAX_MAPS,
    TED5_SIGNATURE,
    Archive,
    MapRecord,
    encode_archive,
    parse_archive,
)
from ec7edit_core.errors import DiagnosticLog, NativeFormatError
from ec7edit_core.names import NativeName
from ec7edit_core.planes import MAX_DIMENSION, MapPlanes

_spec = importlib.util.spec_from_file_location(
    "make_fixtures", EDITOR / "scripts" / "make_fixtures.py")
make_fixtures = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(make_fixtures)


def record(number=1, name="LAB", width=4, height=4, salt=0) -> MapRecord:
    planes = tuple(
        tuple((salt * 97 + plane * 31 + cell) % 1000 for cell in range(width * height))
        for plane in range(3)
    )
    return MapRecord(number, NativeName.from_text(name), MapPlanes(width, height, planes))


class HeaderLayout(unittest.TestCase):
    def test_first_record_is_46_bytes_with_an_implicit_plane_zero(self):
        blob = encode_archive([record()])
        self.assertEqual(blob[:12], TED5_SIGNATURE)
        # Plane 0's offset is stored nowhere: the stream simply starts at 46.
        # Offsets 12 and 16 are planes 1 and 2, which is why the record is 46
        # bytes rather than the 50 a naive reading of "three offsets" gives.
        plane1, plane2 = struct.unpack_from("<II", blob, 12)
        length0, length1, length2 = struct.unpack_from("<HHH", blob, 20)
        self.assertEqual(FIRST_RECORD_BYTES + length0, plane1)
        self.assertEqual(plane1 + length1, plane2)
        self.assertEqual(struct.unpack_from("<HH", blob, 26), (4, 4))

    def test_later_records_are_42_bytes_and_start_with_the_marker(self):
        blob = encode_archive([record(1), record(2, "TWO", salt=1)])
        second = blob.index(MAP_MARKER, FIRST_RECORD_BYTES)
        self.assertEqual(blob[second : second + 4], MAP_MARKER)
        offsets = struct.unpack_from("<III", blob, second + 4)
        self.assertEqual(offsets[0], second + LATER_RECORD_BYTES)

    def test_archive_ends_with_a_bare_marker(self):
        self.assertTrue(encode_archive([record()]).endswith(MAP_MARKER))

    def test_each_header_is_followed_by_its_own_planes(self):
        blob = encode_archive([record(1), record(2, "TWO", salt=1)])
        parsed = parse_archive(blob)
        first, second = parsed.records
        self.assertLess(first.source.plane_offsets[2], second.source.header_offset)
        self.assertLess(second.source.header_offset, second.source.plane_offsets[0])


class RoundTrip(unittest.TestCase):
    def assertSurvives(self, records):
        parsed = parse_archive(encode_archive(records))
        self.assertEqual(len(parsed), len(records))
        for original, seen in zip(records, parsed.records):
            self.assertEqual(seen.name.raw, original.name.raw)
            self.assertEqual(seen.planes.planes, original.planes.planes)
            self.assertEqual((seen.width, seen.height), (original.width, original.height))
        return parsed

    def test_one_map(self):
        self.assertSurvives([record()])

    def test_sixty_maps_like_the_shipped_archive(self):
        self.assertSurvives([record(n + 1, f"MAP {n + 1}", 16, 16, n) for n in range(60)])

    def test_the_maximum_map_count(self):
        self.assertSurvives([record(n + 1, f"M{n}", 2, 2, n) for n in range(MAX_MAPS)])

    def test_rectangular_and_extreme_dimensions(self):
        for width, height in ((1, 1), (1, 64), (64, 1), (64, 64), (MAX_DIMENSION, 1)):
            with self.subTest(size=(width, height)):
                self.assertSurvives([record(1, "EDGE", width, height)])

    def test_the_largest_map_the_engine_allows(self):
        # 181x181 expands to 65522 bytes, thirteen short of the size field's
        # ceiling. One cell more and the format cannot describe it at all.
        blank = (0,) * (MAX_DIMENSION * MAX_DIMENSION)
        planes = MapPlanes(MAX_DIMENSION, MAX_DIMENSION, (blank, blank, blank))
        self.assertSurvives([MapRecord(1, NativeName.from_text("MAX"), planes)])

    def test_all_three_planes_are_independent(self):
        planes = MapPlanes(2, 2, ((1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12)))
        parsed = self.assertSurvives([MapRecord(1, NativeName.from_text("P"), planes)])
        self.assertEqual(parsed[0].planes.planes[2], (9, 10, 11, 12))

    def test_encoding_is_reproducible(self):
        records = [record(1), record(2, "TWO", salt=3)]
        self.assertEqual(encode_archive(records), encode_archive(records))


class ReadsTheFixtureCorpus(unittest.TestCase):
    """The fixtures come from a different encoder; that is the point."""

    def setUp(self):
        self.fixtures = make_fixtures.fixture_set()

    def test_reads_a_single_map_fixture(self):
        parsed = parse_archive(self.fixtures["archive/one-map.c7map"])
        self.assertEqual(len(parsed), 1)
        self.assertEqual(parsed[0].name.text, "SYNTH01")
        self.assertEqual((parsed[0].width, parsed[0].height), (8, 8))

    def test_reads_a_three_map_fixture(self):
        parsed = parse_archive(self.fixtures["archive/three-maps.c7map"])
        self.assertEqual([r.name.text for r in parsed], ["SYNTH01", "SYNTH02", "SYNTH03"])
        self.assertEqual([(r.width, r.height) for r in parsed], [(8, 8), (16, 16), (64, 64)])

    def test_a_foreign_encoding_re_encodes_to_the_same_map(self):
        # The fixture generator's run threshold is three and ours is four, so
        # the bytes may or may not coincide depending on the plane. What must
        # hold either way is that the map itself survives being rewritten.
        original = self.fixtures["archive/three-maps.c7map"]
        parsed = parse_archive(original)
        rewritten = parse_archive(encode_archive(parsed.records))
        self.assertEqual(
            [r.planes.planes for r in rewritten],
            [r.planes.planes for r in parsed],
        )
        self.assertEqual([r.name.raw for r in rewritten], [r.name.raw for r in parsed])

    def test_every_malformed_fixture_is_refused(self):
        malformed = {k: v for k, v in self.fixtures.items() if k.startswith("malformed/")}
        self.assertGreaterEqual(len(malformed), 8)
        for name, blob in malformed.items():
            with self.subTest(fixture=name):
                with self.assertRaises(NativeFormatError):
                    parse_archive(blob)

    def test_the_no_terminator_fixture_loads_with_a_warning(self):
        log = DiagnosticLog()
        parsed = parse_archive(self.fixtures["archive/no-final-marker.c7map"], log=log)
        self.assertEqual(len(parsed), 1)
        self.assertFalse(parsed.terminated)
        self.assertIn("C7E-NATIVE-005", log.codes())


class Rejects(unittest.TestCase):
    def assertRefused(self, blob, fragment=""):
        with self.assertRaises(NativeFormatError) as caught:
            parse_archive(blob)
        if fragment:
            self.assertIn(fragment, str(caught.exception))
        return caught.exception

    def test_empty_file(self):
        self.assertRefused(b"", "no maps")

    def test_marker_only_file(self):
        self.assertRefused(MAP_MARKER, "no maps")

    def test_bad_signature(self):
        good = bytearray(encode_archive([record()]))
        good[3] = ord("4")
        self.assertRefused(bytes(good), "signature")

    def test_dimensions_past_the_engine_limit(self):
        good = bytearray(encode_archive([record()]))
        struct.pack_into("<HH", good, 26, MAX_DIMENSION + 1, 4)
        self.assertRefused(bytes(good), "outside the engine's")

    def test_zero_dimension(self):
        good = bytearray(encode_archive([record()]))
        struct.pack_into("<HH", good, 26, 0, 4)
        self.assertRefused(bytes(good))

    def test_plane_running_past_the_end_of_the_file(self):
        good = bytearray(encode_archive([record()]))
        struct.pack_into("<H", good, 20, 0xFFFF)
        self.assertRefused(bytes(good), "past the end")

    def test_descending_plane_offsets(self):
        good = bytearray(encode_archive([record()]))
        plane1, plane2 = struct.unpack_from("<II", good, 12)
        struct.pack_into("<II", good, 12, plane2, plane1)
        self.assertRefused(bytes(good), "overlapping")

    def test_later_plane_zero_inside_its_own_header(self):
        good = bytearray(encode_archive([record(1), record(2, "TWO", salt=1)]))
        second = good.index(MAP_MARKER, FIRST_RECORD_BYTES)
        struct.pack_into("<I", good, second + 4, second + 8)
        self.assertRefused(bytes(good), "inside its own")

    def test_trailing_bytes(self):
        # The engine only reads a terminator when exactly four bytes remain,
        # so anything after one is the start of a record that is not there.
        self.assertRefused(encode_archive([record()]) + b"\x00\x00", "too few for a")

    def test_more_than_the_engines_map_limit(self):
        with self.assertRaises(NativeFormatError) as caught:
            encode_archive([record(n + 1, f"M{n}", 2, 2, n) for n in range(MAX_MAPS + 1)])
        self.assertEqual(caught.exception.diagnostic.code, "C7E-NATIVE-001")

    def test_no_maps_at_all(self):
        with self.assertRaises(NativeFormatError):
            encode_archive([])


class Names(unittest.TestCase):
    def test_display_stops_at_the_first_nul(self):
        name = NativeName.from_raw(b"LOBBY\x00rubbish\x00\x00\x00")
        self.assertEqual(name.text, "LOBBY")

    def test_bytes_after_the_nul_survive_a_round_trip(self):
        raw = b"SLOT\x00\x001\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        original = MapRecord(1, NativeName.from_raw(raw), MapPlanes.empty(2, 2))
        parsed = parse_archive(encode_archive([original]))
        self.assertEqual(parsed[0].name.raw, raw)
        self.assertEqual(parsed[0].name.text, "SLOT")

    def test_a_preserved_noncanonical_name_reports_007_not_004(self):
        raw = b"SLOT\x00\x001\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        log = DiagnosticLog()
        parse_archive(
            encode_archive([MapRecord(1, NativeName.from_raw(raw), MapPlanes.empty(2, 2))]),
            log=log,
        )
        self.assertEqual(log.codes(), ["C7E-NATIVE-007"])

    def test_a_canonical_imported_name_says_nothing(self):
        log = DiagnosticLog()
        parse_archive(encode_archive([record()]), log=log)
        self.assertEqual(log.codes(), [])

    def test_renaming_replaces_the_whole_field(self):
        stale = NativeName.from_raw(b"OLD\x00\x00\x99\x99" + b"\x00" * 9)
        renamed = NativeName.from_text("NEW")
        self.assertEqual(renamed.raw, b"NEW" + b"\x00" * 13)
        self.assertNotIn(b"\x99", renamed.raw)
        self.assertFalse(stale.is_canonical)
        self.assertTrue(renamed.is_canonical)

    def test_an_unencodable_rename_is_refused(self):
        for bad in ("x" * 16, "café", "tab\there"):
            with self.subTest(name=bad):
                with self.assertRaises(NativeFormatError) as caught:
                    NativeName.from_text(bad)
                self.assertEqual(caught.exception.diagnostic.code, "C7E-NATIVE-004")

    def test_fifteen_bytes_is_the_longest_canonical_name(self):
        self.assertTrue(NativeName.from_text("x" * 15).is_canonical)

    def test_a_full_sixteen_byte_field_has_nowhere_for_a_terminator(self):
        self.assertFalse(NativeName.from_raw(b"x" * 16).is_canonical)

    def test_a_name_field_of_the_wrong_size_is_refused(self):
        with self.assertRaises(NativeFormatError):
            NativeName.from_raw(b"short")


class LumpNames(unittest.TestCase):
    def test_slots_map_to_engine_lump_names(self):
        self.assertEqual(record(1).lump_name, "MAP01")
        self.assertEqual(record(9).lump_name, "MAP09")
        self.assertEqual(record(60).lump_name, "MAP60")

    def test_the_hundredth_slot_is_three_digits(self):
        # mysnprintf(..., "MAP%02d", i+1) widens rather than truncates, and
        # MAP100 still fits a WAD's eight-byte name field.
        self.assertEqual(record(100).lump_name, "MAP100")


if __name__ == "__main__":
    unittest.main(verbosity=1)


class ReplaceRecords(unittest.TestCase):
    """E8's private full-archive export: your maps in their slots, every other
    map copied through untouched."""

    def archive(self, count=3):
        from ec7edit_core.archive import Archive, MapRecord
        from ec7edit_core.names import NativeName
        from ec7edit_core.planes import MapPlanes

        records = []
        for number in range(1, count + 1):
            cells = tuple(number for _ in range(4 * 4))
            records.append(MapRecord(
                number=number,
                name=NativeName.from_text(f"MAP {number}"),
                planes=MapPlanes(4, 4, (cells, cells, cells)),
            ))
        return Archive(tuple(records))

    def test_replacing_nothing_is_a_faithful_copy(self):
        from ec7edit_core.archive import encode_archive, replace_records

        source = self.archive()
        self.assertEqual(replace_records(source, {}),
                         encode_archive(source.records))

    def test_the_named_slot_is_replaced(self):
        from ec7edit_core.archive import parse_archive, replace_records

        source = self.archive()
        blob = replace_records(source, {2: source.by_number(3)})
        back = parse_archive(blob)
        self.assertEqual(back.by_number(2).planes, source.by_number(3).planes)

    def test_the_others_are_untouched(self):
        from ec7edit_core.archive import parse_archive, replace_records

        source = self.archive()
        back = parse_archive(replace_records(source, {2: source.by_number(3)}))
        for number in (1, 3):
            self.assertEqual(back.by_number(number).planes,
                             source.by_number(number).planes)

    def test_a_replacement_keeps_the_slot_it_lands_in(self):
        # The record being written in carries its own number; the slot it goes
        # to is the one asked for, or the archive would come back reordered.
        from ec7edit_core.archive import parse_archive, replace_records

        source = self.archive()
        back = parse_archive(replace_records(source, {2: source.by_number(3)}))
        self.assertEqual([r.number for r in back.records], [1, 2, 3])

    def test_a_slot_the_archive_does_not_have_is_refused(self):
        # An append would produce a file the engine indexes differently from
        # the one the user thinks they have.
        from ec7edit_core.archive import replace_records
        from ec7edit_core.errors import Ec7EditError

        source = self.archive()
        with self.assertRaises(Ec7EditError):
            replace_records(source, {9: source.by_number(1)})
