#!/usr/bin/env python3
"""Build native palette-swap sprite definitions; contains no retail artwork.

The engine composes every variant from the user's installed MARN sprites.
Run with --check to verify the checked-in generated definitions.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Source blue ramp is 40..63. Leave its unused black entry 40 alone.
# All destination ramps are ordinary, non-luminous palette entries.
COLORS = (
    ("Red", "MRRD", 65, 87),
    ("Green", "MRGN", 113, 135),
    ("Gold", "MRGD", 89, 111),
    ("Purple", "MRPR", 185, 207),
    ("Magenta", "MRMG", 161, 183),
    ("Brown", "MRBR", 137, 159),
    ("Gray", "MRGY", 17, 39),
)
FRAMES = [f"{frame}{rotation}" for frame in "ABCDE" for rotation in range(1, 9)]
FRAMES += [f"{frame}0" for frame in "FGHIJKLMNOP"]
MARKER = "// BEGIN GENERATED CORRIDOR 7 PLAYER COLORS\n"


def textures():
    result = [MARKER, "// Generated by tools/make_c7_player_colors.py. Reuses installed art.\n"]
    for color, bank, first, last in COLORS:
        result.append(f"\n// {color}: blue uniform only. Original canvas and pivot.\n")
        for frame in FRAMES:
            result.append(f'''sprite optional "{bank}{frame}", 64, 64
{{
    Offset 32, 64
    Sprite "MARN{frame}", 32, 64
    {{
        UseOffsets
        Translation "41:63={first}:{last}"
    }}
}}
''')
    return "".join(result)


def actors():
    result = ["// Generated by tools/make_c7_player_colors.py.\n",
              "// Cosmetic subclasses: all gameplay properties are inherited.\n"]
    for color, bank, _, _ in COLORS:
        result.append(f'''
actor C7Player{color} : C7Player
{{
    player.displayname "Marine ({color.lower()})"
    states
    {{
        Spawn:
            {bank} A -1
            stop
        See:
            {bank} ABCDE 3
            loop
        Missile:
            {bank} NOP 6 bright
            goto See
        Melee:
            {bank} NO 6 bright
            goto See
        Pain:
            {bank} F 5
            goto See
        Death:
            {bank} G 0 A_Scream
            {bank} G 5 A_Fall
            {bank} HIJKL 5
            {bank} M -1
            stop
    }}
}}
''')
    return "".join(result)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    texture_file = ROOT / "wadsrc/static/textures.txt"
    prefix = texture_file.read_text().split(MARKER)[0].rstrip() + "\n\n"
    outputs = {
        texture_file: prefix + textures(),
        ROOT / "wadsrc/static/actors/corridor7/playercolors.txt": actors(),
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale generated file: {path}")
        else:
            path.write_text(content)
    print(f"{'Checked' if args.check else 'Created'} {len(COLORS)} colors, "
          f"{len(FRAMES)} frames each ({len(COLORS) * len(FRAMES)} sprites).")


if __name__ == "__main__":
    main()
