#!/bin/sh

# Build a self-contained EC7Edit package: the editor, a Python, and Qt.
#
# The editor is pure Python in two packages -- ec7edit_core, which depends on
# nothing but the standard library, and ec7edit_gui, which needs PySide6. That
# is a fine way to develop and a poor way to hand somebody an editor, because
# it makes their machine's Python and their Qt version part of the product. So
# this freezes the lot into a directory that runs on its own.
#
# ONEDIR, not onefile, and that was measured rather than assumed (E4 ledger,
# editor/docs/e4-evidence-ledger.md): compressed they are the same download --
# 72.8 MB against 72.1 -- and onefile unpacks itself into a temporary directory
# on every single launch, which costs about a second each time. Right for the
# installer, which somebody runs once; wrong for an editor that is opened and
# closed all day. Median start is 0.22 s against 1.19 s.
#
# The package is DATA-FREE and this script keeps it that way: it copies the
# editor's own sources and its catalogue and nothing else, and the audit at the
# end fails if a Corridor 7 file, or anything the size of one, got in.
#
# Usage: package_ec7edit.sh --output DIR [--python PYTHON] [--no-archive]

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo=$(CDPATH= cd -- "$here/.." && pwd)
editor="$repo/editor"

output=""
python=""
archive=1
while [ "$#" -gt 0 ]; do
	case $1 in
		--output) output=$2; shift 2 ;;
		--python) python=$2; shift 2 ;;
		--no-archive) archive=0; shift ;;
		-h|--help) sed -n '3,20p' "$0"; exit 0 ;;
		*) printf 'unknown option %s\n' "$1" >&2; exit 2 ;;
	esac
done

[ -n "$output" ] || { printf 'usage: %s --output DIR\n' "$0" >&2; exit 2; }

# The interpreter that will be frozen INTO the package, so this is the version
# users get. editor/.venv is the reference runtime -- Python 3.12 with a pinned
# PySide6 -- and falling back to whatever python3 is on PATH would quietly ship
# a different one.
if [ -z "$python" ]; then
	if [ -x "$editor/.venv/bin/python" ]; then
		python="$editor/.venv/bin/python"
	elif [ -x "$editor/.venv/Scripts/python.exe" ]; then
		python="$editor/.venv/Scripts/python.exe"
	else
		python=python3
	fi
fi

"$python" -c 'import PyInstaller' 2>/dev/null || {
	printf 'SKIP: %s has no PyInstaller, so there is nothing to freeze with.\n' "$python"
	printf '      python -m pip install pyinstaller, or pass --python\n'
	exit 0
}
"$python" -c 'import PySide6' 2>/dev/null || {
	printf 'SKIP: %s has no PySide6.\n' "$python"
	exit 0
}

version=$("$python" -c "import sys; sys.path.insert(0, '$editor'); \
	from ec7edit_core import __version__; print(__version__)" 2>/dev/null || echo unknown)

# Stamped into the package, because there is no repository inside one to ask.
# Written before the freeze so PyInstaller picks it up as an ordinary module,
# and removed afterwards -- a generated file left in the tree would be the next
# checkout's stale answer.
stamp="$editor/ec7edit_core/_build_version.py"
cat >"$stamp" <<EOF
# Generated by tools/package_ec7edit.sh. Not committed, not edited by hand.
VERSION = "$version"
EOF
cleanup_stamp() { rm -f "$stamp"; }
trap 'cleanup_stamp; rm -rf "${work:-}"' EXIT INT TERM
runtime=$("$python" -c 'import sys; print(".".join(map(str, sys.version_info[:3])))')
qt=$("$python" -c 'import PySide6; print(PySide6.__version__)')

case $(uname -s 2>/dev/null || echo unknown) in
	Linux)  platform=linux ;;
	Darwin) platform=macos ;;
	MINGW*|MSYS*|CYGWIN*) platform=windows ;;
	*)      platform=unknown ;;
esac
arch=$(uname -m 2>/dev/null || echo unknown)
name="ec7edit-$version-$platform-$arch"

printf 'EC7Edit %s -- freezing with Python %s and PySide6 %s\n' "$version" "$runtime" "$qt"

work=$(mktemp -d /tmp/ec7edit-package.XXXXXX)

# --- freeze ----------------------------------------------------------------
#
# Qt is enormous and most of it is not used. Excluding the modules the editor
# never imports is the difference between a package somebody downloads and one
# they give up on -- and an exclusion that is wrong shows up immediately as an
# editor that will not start, which the startup gate runs straight afterwards.
( cd "$editor" && "$python" -m PyInstaller \
	--noconfirm --clean --log-level WARN \
	--distpath "$work/dist" --workpath "$work/build" --specpath "$work" \
	`# --add-data sources resolve against --specpath, not the working` \
	`# directory, so this one is absolute; a relative path here fails` \
	`# with "unable to find" naming a file in the temporary spec dir.` \
	--name ec7edit --windowed --onedir \
	--add-data "$editor/resources/editor_catalog.json:resources" \
	--hidden-import ec7edit_gui.application \
	--hidden-import ec7edit_core._build_version \
	--exclude-module tkinter \
	--exclude-module PySide6.QtWebEngineCore \
	--exclude-module PySide6.QtWebEngineWidgets \
	--exclude-module PySide6.QtQuick \
	--exclude-module PySide6.QtQml \
	--exclude-module PySide6.Qt3DCore \
	--exclude-module PySide6.QtMultimedia \
	--exclude-module PySide6.QtCharts \
	--exclude-module PySide6.QtDataVisualization \
	ec7edit ) >"$work/freeze.log" 2>&1 || {
	printf 'FAIL: PyInstaller did not finish\n' >&2
	tail -25 "$work/freeze.log" >&2
	exit 1
}

[ -x "$work/dist/ec7edit/ec7edit" ] || [ -f "$work/dist/ec7edit/ec7edit.exe" ] || {
	printf 'FAIL: the freeze produced no executable\n' >&2
	tail -25 "$work/freeze.log" >&2
	exit 1
}

# --- assemble --------------------------------------------------------------
staging="$work/$name"
mv "$work/dist/ec7edit" "$staging"

cp "$repo/docs/license-gpl.txt" "$staging/LICENSE.txt"

# What else is in the box, and under what terms. A package that bundles a Qt
# and a Python owes their licences too, and "it is only a dependency" stops
# being true the moment the libraries are inside the file being distributed.
# Versions are read from the environment that was frozen rather than typed
# here, so this cannot describe a Qt the package does not contain.
"$python" - "$staging/THIRD-PARTY.txt" "$runtime" <<'PY' || true
import sys
from pathlib import Path

try:
    import importlib.metadata as metadata
except ImportError:                                   # pragma: no cover
    metadata = None

lines = [
    "Third-party software inside this package",
    "========================================",
    "",
    "EC7Edit itself is GPL-3.0-or-later; see LICENSE.txt. This package also",
    "contains the following, which are not ours and keep their own terms.",
    "",
]

if metadata is not None:
    for name in ("PySide6", "PySide6-Essentials", "PySide6-Addons", "shiboken6"):
        try:
            md = metadata.metadata(name)
        except Exception:
            continue
        licence = md.get("License-Expression") or md.get("License") or "see the project"
        lines.append(f"  {name} {md.get('Version')}")
        lines.append(f"      {licence}")
        lines.append("      Qt itself is included, under the same terms.")
        lines.append("      https://www.qt.io/licensing  https://pypi.org/project/PySide6/")
        lines.append("")

lines += [
    f"  CPython {sys.argv[2]}",
    "      Python Software Foundation License 2.0",
    "      https://docs.python.org/3/license.html",
    "",
    "  PyInstaller runtime (the bootloader in this executable)",
    "      GPL-2.0-or-later with the bootloader exception, which permits",
    "      shipping frozen applications under any licence.",
    "      https://pyinstaller.org/en/stable/license.html",
    "",
    "No part of Corridor 7: Alien Invasion is in this package. That game",
    "remains the property of its owners and must be obtained separately.",
    "",
]
Path(sys.argv[1]).write_text("\n".join(lines))
print(f"  licenses: {Path(sys.argv[1]).name}")
PY
[ -f "$repo/docs/ec7edit-manual.md" ] && cp "$repo/docs/ec7edit-manual.md" "$staging/MANUAL.md"

cat >"$staging/README.txt" <<EOF
EC7Edit $version -- a level editor for Corridor 7: Alien Invasion
$(printf '%s' "----------------------------------------------------------------")

Run ./ec7edit (ec7edit.exe on Windows). Everything it needs to start is in this
folder: a Python $runtime and Qt $qt are inside it, and nothing has to be
installed first.

THIS PACKAGE CONTAINS NO PART OF CORRIDOR 7. It holds an editor and nothing
else -- no maps, no artwork, no sounds. To edit or play anything you need your
own copy of the game, and EC7Wolf to run it with. The editor asks for both the
first time it starts.

MANUAL.md is the full manual. The project lives at
https://github.com/jeddhor/EC7Wolf

Licensed GPL-3.0-or-later; see LICENSE.txt.
EOF

# --- the audit -------------------------------------------------------------
#
# A public artifact, so the question is not "did I mean to include game data"
# but "is any in here". Asked of the built tree, by looking.
"$python" - "$staging" <<'PY' || exit 1
import sys
from pathlib import Path

root = Path(sys.argv[1])
BANNED_SUFFIX = {".co7", ".wad", ".exe~", ".ec7project", ".vswap", ".vgagraph"}
BANNED_NAME = {"corr7cd.exe", "maptemp.co7", "maphead.co7", "gfxtiles.co7"}

bad = []
for path in sorted(root.rglob("*")):
    if not path.is_file():
        continue
    lowered = path.name.lower()
    if lowered in BANNED_NAME or Path(lowered).suffix in BANNED_SUFFIX:
        bad.append(str(path.relative_to(root)))
if bad:
    sys.exit("FAIL: the package holds game data: " + ", ".join(bad[:8]))

total = sum(p.lstat().st_size for p in root.rglob("*") if p.is_file())
print(f"  audit: {sum(1 for p in root.rglob('*') if p.is_file())} files, "
      f"{total / 1e6:.1f} MB, no Corridor 7 content")
PY

mkdir -p "$output"
outdir=$(cd "$output" && pwd)
rm -rf "$outdir/$name"
cp -a "$staging" "$outdir/$name"
printf '  package: %s\n' "$outdir/$name"

if [ "$archive" -eq 1 ]; then
	# .zip on Windows and .tar.gz elsewhere: a tar loses nothing that matters
	# on Linux and keeps the executable bit, which a zip does not.
	if [ "$platform" = windows ]; then
		( cd "$outdir" && rm -f "$name.zip" && zip -qr "$name.zip" "$name" )
		printf '  archive: %s.zip (%s)\n' "$outdir/$name" \
			"$(du -h "$outdir/$name.zip" | cut -f1)"
	else
		( cd "$outdir" && rm -f "$name.tar.gz" && tar czf "$name.tar.gz" "$name" )
		printf '  archive: %s.tar.gz (%s)\n' "$outdir/$name" \
			"$(du -h "$outdir/$name.tar.gz" | cut -f1)"
	fi
fi

printf 'PASS: EC7Edit %s packaged for %s-%s.\n' "$version" "$platform" "$arch"
