#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Jason Tripp
"""Write (or check) the validation-code reference from the code itself.

The plan asks E7 for a diagnostic reference. A hand-written one drifts: a rule
gets a new severity or a fix and the table still says what it used to. This
generates the table from what the validator actually does, and `--check` fails
if the committed document no longer matches -- the same contract the catalogue
has.

    validation_reference.py [write|check]
"""

from __future__ import annotations

import sys
from pathlib import Path

EDITOR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(EDITOR))

from ec7edit_core.validation import (  # noqa: E402
    FIXES,
    GLOBAL_CODES,
    LOCAL_CODES,
    PROFILES,
)

DOC = EDITOR.parent / "docs" / "ec7edit-validation.md"

#: One line per code: what it means, and what to do about it. The severity and
#: the scope are read from the validator; only the prose lives here.
CODES = {
    "C7E-BOUNDARY-001": (
        "A cell on the outer ring is walkable, so the player can walk out of "
        "the world.",
        "Paint the ring solid. The one-click fix does it.",
    ),
    "C7E-CELL-002": (
        "An imported word the translation does not define. It is preserved "
        "exactly and never rewritten.",
        "Nothing, unless you meant to replace it.",
    ),
    "C7E-THING-001": (
        "Something on the object plane is standing inside a wall.",
        "Move it onto floor, or clear the wall under it.",
    ),
    "C7E-WALL-001": (
        "A wall modifier -- a pushwall, a disintegrating wall -- has no wall "
        "to act on.",
        "Put a solid wall in the same cell, or remove the marker.",
    ),
    "C7E-ZONE-001": (
        "Floor with no sound area. Areas are how the engine carries noise: a "
        "cell with none is a cell nothing can hear the player through, so "
        "aliens ignore gunfire and wake only on sight or contact.",
        "Tools > Give the floor sound areas.",
    ),
    "C7E-START-001": ("No player start.", "Place one on floor."),
    "C7E-START-002": (
        "More than the profile allows. A campaign floor takes one; an arena "
        "takes as many as it has spawn points.",
        "Remove the extras, or check the slot this map is exported to.",
    ),
    "C7E-START-003": ("A player start is inside a wall.", "Move it onto floor."),
    "C7E-DOOR-003": (
        "A locked door whose card is nowhere on the floor -- neither lying "
        "about nor granted by a terminal of that colour.",
        "Place the card or its terminal, or unlock the door.",
    ),
    "C7E-DOOR-004": (
        "The card that opens a door is behind that door. The reachability "
        "flood is a fixpoint, so a colour still blocking when it stops is one "
        "the player can never hold.",
        "Move the card, or the door.",
    ),
    "C7E-EXIT-001": (
        "No way to finish the floor, or none the player can reach.",
        "Place an elevator switch, a floor exit or an exit vortex where the "
        "player can get to it.",
    ),
    "C7E-ZONE-002": (
        "Floor the player can never stand on. Pushwalls are treated as routes, "
        "so a secret room is not this; a sealed pocket is.",
        "Connect it, or leave it if it is deliberate scenery.",
    ),
    "C7E-WARP-001": (
        "A transporter channel with other than two endpoints.",
        "Use the transporter pair tool, which places both ends at once.",
    ),
    "C7E-DOOR-001": (
        "A door without two opposing floor approaches. Corridor 7 infers a "
        "door's axis from the floor around it, so this one may not open the "
        "way it looks.",
        "Reshape the corridor, or confirm the topology is what you meant.",
    ),
    "C7E-DOOR-002": (
        "A door whose axis is a tie. The engine breaks ties one way; an editor "
        "that guessed the other would show one thing and ship another.",
        "Adjust a neighbouring cell so the axis is unambiguous.",
    ),
}


def render() -> str:
    lines = [
        "# EC7Edit validation codes",
        "",
        "Generated by `editor/scripts/validation_reference.py` from the validator",
        "itself -- the scope and the fix column are read from the code, so this",
        "cannot drift from what the editor does. Run it with `check` to prove it.",
        "",
        "A code is the contract. Messages are free to improve; tests, the GUI and",
        "this document all key on the code.",
        "",
        "## Profiles",
        "",
        "The same map is right or wrong depending on where it is going, so every",
        "rule is asked in the context of the slot the map is exported to.",
        "",
        "| Profile | Player starts | Needs an exit | Reports unreachable floor |",
        "| --- | --- | --- | --- |",
    ]
    for profile in PROFILES.values():
        starts = "any" if profile.starts is None else str(profile.starts)
        lines.append(f"| `{profile.key}` | {starts} | "
                     f"{'yes' if profile.needs_exit else 'no'} | "
                     f"{'yes' if profile.reports_unreachable else 'no'} |")
    lines += [
        "",
        "## Codes",
        "",
        "**Scope** is `local` for a rule whose answer depends only on the cells",
        "around the one that changed -- those run on every edit -- and `map` for",
        "one that is a claim about the whole floor, which runs when the hand",
        "stops and before anything is exported.",
        "",
        "| Code | Scope | Fix | Condition | What to do |",
        "| --- | --- | --- | --- | --- |",
    ]
    fix_for = {"C7E-BOUNDARY-001": "seal_boundary", "C7E-ZONE-001": "sound_areas"}
    for code, (condition, action) in sorted(CODES.items()):
        scope = "local" if code in LOCAL_CODES else ("map" if code in GLOBAL_CODES else "—")
        fix = fix_for.get(code, "")
        fix_cell = f"`{fix}`" if fix else "—"
        lines.append(f"| `{code}` | {scope} | {fix_cell} | {condition} | {action} |")
    lines += [
        "",
        "## Severity",
        "",
        "An error blocks an export; a warning does not. The same finding is an",
        "error in a map somebody is drawing and a warning in one imported from",
        "the retail archive, because an unexpected word in shipped data is",
        "evidence about the original rather than a mistake to correct. Across",
        "all sixty shipped maps the validator reports **no errors**, which is the",
        "false-positive review the plan asks for.",
        "",
        "## Repairs",
        "",
        "A repair is offered only where there is exactly one thing the author can",
        "have meant, and it is an ordinary command: one undo, no path that edits",
        "a document behind the history's back.",
        "",
    ]
    for key, (label, _) in sorted(FIXES.items()):
        lines.append(f"- `{key}` — {label}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    mode = argv[1] if len(argv) > 1 else "check"
    text = render()
    if mode == "write":
        DOC.write_text(text, encoding="utf-8")
        print(f"wrote {DOC} ({len(CODES)} codes)")
        return 0
    if not DOC.exists():
        print(f"{DOC} is missing; run with 'write'", file=sys.stderr)
        return 1
    if DOC.read_text(encoding="utf-8") != text:
        print(f"{DOC} is stale; regenerate it and review the diff", file=sys.stderr)
        return 1
    print(f"{DOC.name}: current ({len(CODES)} codes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
